language: node_js
node_js:
  - '6'
sudo: false
addons:
  sauce_connect:
    username: metal-uri
    no_ssl_bump_domains: all
  jwt:
    secure: ExOtmzQoKR2PvdKvsgEai/7/uLD1+9uKiovZS65r9B1W1uZxwd9BIENxOv5RLt5j1YFN94Ri695c7uXRq8leE6mW/Zr+nBWkxG5twZF9t58oqsGv3JgynRJKSxB9MA22EAZmKfKsM1d03e1wFpM/gQ6AIFRLHsOJngUeBTqtaXLCaanKNdVfLVQXNwxz3lIqZkuv/fDP45LZyMtjxmmpPVHOQWFFoO1cZi8b1Nolb+rVdXBzDv0g3YMDI0ZQmNVEUHYq9muzIzuQvpiudZ3ewzuEgTZ5QKCVGMBWvl+RLmNAMOiUFYAbaGpZjZ0aanoZEyyFVUgHdgad7yTEQSD0CIWW/V9O6+FoYW490TeLzkj1cL7apxmakUHmuBj9uKCzW6Thyb5G/9+uCp3r1NSy+TK36PNJS6ozL1fOEnOV9gzovgXW34+G7ikx1RRKQRfi1wu4BnjIGJnN0avM5wXBHpTUGFJTznQG4voVAIv7jBJderndZSuIIUiDL8AA/tjuSS600DRqGRLLBTn0QEQsjaj5aZJxSCF4Sc76rabMn6iazGQhUZST5eI2E3ajswTBhkgVNACiZEMLuzozW31dBX9FZfSMiKET2vY8IRGpy3gFXxOJRLZGn8qVVbELCDdbEFEyBB3/h6mKCYx2pstbUxBW/kdm4MdVfBG3lfgyD8Y=
before_install:
  - npm install
script: npm run test:saucelabs
